### ISSUE TITLE
The importance of BaseNuGetRuntimeIdentifier

### ISSUE THREAD

**Issue by DamianReeves** [davidfowl/AspNetCoreCsproj#2]
I would suggest that someplace here you should note the importance of **BaseNuGetRuntimeIdentifier** in the .csproj file (at least for RC2). Without it nugget complains about you needing `win` as a runtime.

``` xml
<BaseNuGetRuntimeIdentifier>win7-x86</BaseNuGetRuntimeIdentifier>
```

_I'm intentionally putting this here because I've been hit by this multiple times and just realized this was the problem. I'm placing this at the most relevant location so that hopefully someone else can find this._

**Comment by tonysneed** [comment]
@davidfowl For RTM is this still a thing?

**Comment by davidfowl** [comment]
Once the csproj support is done in vs2017 this wont be needed.

**Comment by tonysneed** [comment]
Good news .. thanks!
